name: Build & Publish Desktop Binaries

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - win-x64
          - linux-x64
          - osx-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish for ${{ matrix.runtime }}
        run: |
          dotnet publish --configuration Release \
            --runtime ${{ matrix.runtime }} \
            --self-contained true \
            -o ./publish/${{ matrix.runtime }}

      - name: Prepare artifacts folder
        run: mkdir -p artifacts

      - name: Zip ${{ matrix.runtime }} build
        run: |
          cd publish/${{ matrix.runtime }}
          zip -r ../../../artifacts/artifacts-${{ matrix.runtime }}.zip .

      - name: Upload intermediate artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtime-${{ matrix.runtime }}
          path: artifacts/artifacts-${{ matrix.runtime }}.zip

  release:
    needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
      - name: Download all runtime zips
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body: Automated build for ${{ github.ref_name }} by ${{ github.actor }}.
          files: |
            ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
