name: Build and Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0, v1.0.6, …

env:
  PROJECT_NAME: SimpleAgentModel

jobs:
  build:
    name: Build, Rename & Publish Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish single-file build for ${{ matrix.os }}
        run: |
          dotnet publish -c Release -r ${{ matrix.os }} \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:PublishTrimmed=false \
            --self-contained true \
            -o ./publish/${{ matrix.os }}

      - name: Rename executable & strip out PDBs
        shell: bash
        run: |
          set -e
          dst="publish/${{ matrix.os }}"
          rid="${{ matrix.os }}"
          base="${{ env.PROJECT_NAME }}-${rid}"

          echo "Looking in $dst for the single-file executable…"
          exe="$(find "$dst" -maxdepth 1 -type f ! -name '*.pdb' | head -n1)"
          if [[ -z "$exe" ]]; then
            echo "❌ No executable found in $dst"
            exit 1
          fi

          # compute new name (with .exe on Windows)
          if [[ "$exe" == *.exe ]]; then
            newexe="$dst/${base}.exe"
          else
            newexe="$dst/${base}"
          fi

          echo "Renaming $(basename "$exe") → $(basename "$newexe")"
          mv "$exe" "$newexe"

          # remove any leftover PDBs
          rm -f "$dst"/*.pdb

      - name: Upload renamed executables
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: ./publish/${{ matrix.os }}

  release:
    name: Create GitHub Release & Attach Assets
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all platform artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List files to be released
        run: ls -R ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/binaries-win-x64/*
            artifacts/binaries-linux-x64/*
            artifacts/binaries-osx-x64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
